### ISSUE TITLE
hs-to-coq goes into a seeming infinite loop with memory explosion

### ISSUE THREAD

**Issue by jwiegley** [antalsz/hs-to-coq#112]
1. `git clone https://github.com/SPY/haskell-wasm`

2. `cd haskell-wasm`

3. Use the following `edits` file:

```
rename type Data.ByteString.Lazy.Internal.ByteString = Coq.Strings.String.string
rename type Data.Text.Internal.Lazy.Text = Coq.Strings.String.string
rename type GHC.Natural.Natural = Coq.Numbers.BinNums.N
rename value Language.Wasm.Structure.MemArg = Language.Wasm.Structure.MkMemArg
rename value Language.Wasm.Structure.Limit = Language.Wasm.Structure.MkLimit
```

4. Run the following command:

```
hs-to-coq -e /Users/johnw/src/plclub/hs-to-coq/base/edits -e edits --iface-dir ~/src/plclub/hs-to-coq/base -i src src/Language/Wasm/Structure.hs > Structure.v
```

It's just like crypocurrency mining, just without making any money!

**Comment by emarzion** [comment]
Just thought I'd chime in and say that I've had memory issues as well when translating code with involving large pattern matches, and I believe the culprit is [```isCompleteMultiPattern ```](https://github.com/antalsz/hs-to-coq/blob/01e0ef7fad6f92bf9ac97f9e5824c6f2148a108c/src/lib/HsToCoq/ConvertHaskell/Pattern.hs#L258).  I was able to disable this (it's only invoked twice in [Expr.hs](https://github.com/antalsz/hs-to-coq/blob/acf01b7d8dfd8968069aa21bc5eb8fe90018a786/src/lib/HsToCoq/ConvertHaskell/Expr.hs)) and the memory issues have gone away.

**Comment by nomeata** [comment]
That’s my code, and I would not be surprised if I walk right into some combinatorial explosion while doing pattern exhaustiveness checks – after all, there are whole papers written about that…

**Comment by trommler** [comment]
With #146 applied the above file is translated in under a second using under 200 KB of memory on my machine.
