### ISSUE TITLE
Cannot axiomatize and rename the same module

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#129]
This is really important for `Type`  

Also means that we cannot axiomatize modules that are involved in `Core`

**Comment by antalsz** [comment]
OK, there's two halves to this.  One of them already works, and one doesn't.  Right now, if we have `rename module OldMod NewMod`, then we have to use `axiomatize module NewMod`, and, in my tests, everything works fine.  *However*, because GHC is the only Haskell program in the world to actually use mutually recursive modules, we can't axiomatize only *part* of a translated module cycle.

**Comment by antalsz** [comment]
With the latest commit, 02b84f67c3a7ee4963cf1a2b88fa80fe58aabd4a, this should now be solved.  Use [`axiomatize original module name`](https://hs-to-coq.readthedocs.io/en/latest/edits.html#axiomatize-original-module-name-replace-all-definitions-in-a-module-with-axioms-using-the-pre-renaming-module-name) to axiomatize only part of a merged module group.  If you just need to axiomatize a renamed module, use `axiomatize module RenamedModuleName` instead.

Let me know if you find any bugs!  (You likely will 🙃)
