### ISSUE TITLE
Uniques and UniqSupply need to have native coq implementations

### ISSUE THREAD

**Issue by nomeata** [antalsz/hs-to-coq#4]
I expect that we will have trouble proving anything useful about, say, `CoreSubst` if functions like `uniqAway` or other code that needs to get a fresh `Unique` are not total.

But GHC’s implementation of `Unique` is an `Int`, which is too small to *always* have a fresh one. Further more, `UniqueSupply` uses `unsafePerformIO` and C code to efficiently create new Uniques.

I have the gut feeling that we will have to implement the types `Unique` and `UniqSupply` in Coq, using actual `nat` (or maybe `Char * Integer`) as the representation, and implement `UniqSupply` purely, and have the code translation map operations involving `Unique` and `UniqSupply` use our implementation.

**Comment by sweirich** [comment]
I have translated Uniq and UniqSupply using Char * Integer, which can always produce a fresh Unique. 
However, I just skipped the "mkSplitUniqSupply" function in UniqSupply because it uses the IO monad. Wherever this is used, we'll need to replace the IO monad with something else. When we figure out what that is, we can redefine this function.

**Comment by nomeata** [comment]
I guess this is good enough for now, no need to keep this issue open.
